#!/bin/bash

# customize these
WGET=/usr/bin/wget
ICS2ORG=/home/jschwab/Software/ical2org.py/ical2org.py
CALDIR=/home/jschwab/org/calendar/

# define the calendars we want to fetch
CAL1_NAME=personal
CAL1_URL=$(pass show Calendar/personal-url)

# Check connection status
# This should be replaced with systemd requirements...
if ! ping -c1 www.google.com > /dev/null 2>&1; then
    # Ping could be firewalled ...
    # '-O -' will redirect the actual html to stdout and thus to /dev/null
    if ! wget -O - www.google.com > /dev/null 2>&1; then
        # Both tests failed. We are probably offline
        # (or google is offline, i.e. the end has come)
        echo "$(date) - exiting: no network connection"
        exit 1;
    fi
fi

# go to directory
cd $CALDIR

# get cal 1
$WGET -nv -O ${CAL1_NAME}.ics $CAL1_URL
$ICS2ORG < ${CAL1_NAME}.ics > ${CAL1_NAME}.org
