#!/bin/sh

# from /etc/skel/.xinitrc
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# set HiDPI early on
xrandr --dpi 192
export GDK_SCALE=2
export QT_AUTO_SCREEN_SCALE_FACTOR=1

# if it exists, use .Xresources
if [ -s .Xresources ]; then
    xrdb -merge ~/.Xresources
fi

# switch to set
setxkbmap -option ctrl:swapcaps

# start xbindkeys
xbindkeys

# password and key management
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# fire up the screensaver
xscreensaver -no-splash &

# do xmonad specific things
if [ "${DESKTOP_SESSION}" == "xmonad" ] ; then

    # Set up an icon tray
    trayer --edge top --align right --SetDockType true --SetPartialStrut true \
           --expand true --width 180 --widthtype pixel --height 40 --transparent true --alpha 0 --tint 0x000000 &
fi

if [ -x /usr/bin/nm-applet ] ; then
    nm-applet --sm-disable &
fi

# start pulse audio
#/usr/bin/start-pulseaudio-x11

# turn off bell
xset -b
